From 5a8384ecab188288d3c813fea8f57483c70fd6ec Mon Sep 17 00:00:00 2001
From: GammaC0de <gammac0de@users.noreply.github.com>
Date: Wed, 16 Jun 2021 22:26:13 +0300
Subject: [PATCH 097/150] [TwojlimitPl] sync with stable

---
 src/pyload/plugins/downloaders/TwojlimitPl.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

--- a/src/pyload/plugins/downloaders/TwojlimitPl.py
+++ b/src/pyload/plugins/downloaders/TwojlimitPl.py
@@ -7,7 +7,7 @@ from ..base.multi_downloader import Mult
 class TwojlimitPl(MultiDownloader):
     __name__ = "TwojlimitPl"
     __type__ = "downloader"
-    __version__ = "0.01"
+    __version__ = "0.02"
     __status__ = "testing"
 
     __pattern__ = r"^unmatchable$"
@@ -87,7 +87,7 @@ class TwojlimitPl(MultiDownloader):
         pyfile.size = json_data["filesize"]
 
         try:
-            self.download(self.run_file_query(pyfile.url, "filedownload"), fixurl=False)
+            self.download(self.run_file_query(pyfile.url, "filedownload"))
 
         except Exception as exc:
             self.log_error(exc)
